#내 파일정보
GET http://localhost:3000/user/file/ķŐŸŵŌōĶŦŅœŨŵķŭŸŌŹŸŃĹıłłŚŢťŴœĸńňŖŇŹłŹĹŭķŴŵıŁĽ HTTP/1.1
content-type: application/json

###
#파일 입력

###
#파일 삭제
DELETE http://localhost:3000/user/file/ķŐŸŵŌōĶŦŅœŨŵķŭŸŌŹŸŃĹıłłŚŢťŴœĸńňŖŇŹłŹĹŭķŴŵıŁĽ HTTP/1.1
content-type: application/json

###
#파일 이동
PUT http://localhost:3000/user/file/ŸıĵųŇŵŦťĶŢŹũŉİĹĵŢŉŅĶųťŔŋįŢĸĲŌŢźųŊŚńŗŚŅŔŢŗŤĸĽ HTTP/1.1
content-type: application/json

{
    "folderId": "user1"
}